# Generated by Django 4.2.5 on 2023-10-03 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=120)),
                (
                    "description",
                    models.TextField(blank=True, max_length=800, null=True),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gadget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.TextField(blank=True, max_length=800, null=True),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
                ("price", models.FloatField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gadgets",
                        to="gadgets.brand",
                    ),
                ),
            ],
        ),
    ]
